# Site settings
title: BPR BKK
header-img: images/bprbkk_blog.jpg
email: admin@bprbkk.com
description: >
  BPRBKK atau PD. BPR BKK Kab. Wonogiri merupakan Bank Perkreditan Rakyat
  milik Pemprov Jawa Tengah dan Pemda Kabupaten Wonogiri.
baseurl: ""
url: "http://www.bprbkk.co.id"
timezone: Asia/Jakarta

# Build settings
markdown: kramdown
permalink: pretty

paginate: 8
paginate_path: news/page:num/

sass:
  sass_dir: assets
  style: :compressed